### ISSUE TITLE
API endpoints for categories and receipes

### ISSUE THREAD

**Issue by WeeSee** [k-kaufmann/chefkoch-api#2]
Hi, great idea for an API!
I'm working on some receipe suggestions on Amazon Alexa and 
need some receipes from categiories accessible by API. 
Do you plan to provide categoriy and receipe endpoints in your API?

**Comment by k-kaufmann** [comment]
Hey, sorry for the late reply.

I will continue to work on the API during the week and the next step will be to make it possible to get recipes.
How exactly that will look is still up in the air.
Categories are also being considered, but I can't say exactly when that will be.

**Comment by k-kaufmann** [comment]
Hey, sorry again for the late reply 😅. 

i have added categories support to apiClient. 
To access recipes by categories, you need to call getRecipesByCategories with an array of categories. Categories are unfortunately built in such a way that all subcategories are not automatically searched for as well. This means that you have to pass the subcategories as well if you want to search for them.

I also added that the complete recipes can be requested by ID.
